#ifndef CONSTS_H
#define CONSTS_H

#define MAX_LINE_LENGTH 100000 + 42
#define MAX_CHARS_IN_FILE (2*1024*1024 + 42)
#define MIN_CHARS_TO_ADD_WORD 8
#define MAX_WORDS_IN_FILE (MAX_CHARS_IN_FILE/MIN_CHARS_TO_ADD_WORD)
#define LETTERS_IN_ALPHABET 26

#endif // CONSTS_H
